/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "led.h"
#include "switch_release.h"

#define LED_COUNT 4

int counter = 0;

int main(void) {
	SystemInit();
	SwitchInit();
	LedInit(LED_BLUE_PIN);

	/*while (1) {
	 if (SwitchFlagExti == 1 && counter == 0) {
	 counter++;
	 LedOn(LED_BLUE_PIN);
	 SwitchFlagExti = 0;
	 } else if (SwitchFlagExti == 1 && counter == 1) {
	 counter++;
	 LedOn(LED_GREEN_PIN);
	 SwitchFlagExti = 0;
	 } else if (SwitchFlagExti == 1 && counter == 2) {
	 counter++;
	 LedOn(LED_ORANGE_PIN);
	 SwitchFlagExti = 0;
	 } else if (SwitchFlagExti == 1 && counter == 3) {
	 counter++;
	 LedOn(LED_RED_PIN);
	 SwitchFlagExti = 0;
	 } else
	 ;
	 }*/

	//will check for our flag and once the flag is 1 it will select the led pin from the array we gave and switch it on
	//it will do that until the count is less than the no. of pins
	//and every time it will increment the counter si that it will go to the next pin and turn it on
	while (1) {
		const int ledPins[LED_COUNT] = { LED_BLUE_PIN, LED_GREEN_PIN,
		LED_ORANGE_PIN, LED_RED_PIN };

		if (SwitchFlagExti == 1 && counter < LED_COUNT) {
			LedOn(ledPins[counter]);
			counter++;
			SwitchFlagExti = 0;
		}
	}
	return 0;
}
