/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	//Enable GPIOD.13 CLOCK RCC->AHB1ENR=1
	RCC->AHB1ENR |= BV(3);
	//CONFIGURE GPIOD.13 AS OUTPUT IN MODER [27,26]=01
	GPIOD->MODER &= ~(BV(27)|BV(26));
	//CONFIGURE GPIOD.13 AS OPEN DRAIN IN OTYPER[13]=1
	GPIOD->OTYPER |= BV(13);
	//CONFIGURE GPIOD.13 ASLOW SPEED IN OSPEEDR[27,26]=00
	GPIOD->OSPEEDR &= ~(BV(27)|BV(26));
	//CONFIGURE GPIOD.13 WITH PULL UP RESISTOR PUPDR [27,26]=01
	GPIOD->PUPDR &= ~BV(27);
	GPIOD->PUPDR |= BV(26);
	while(1)
	{
		//CONFIGURE GPIOD.13->ODR =1
		GPIOD->ODR |= BV(13);
		//DELAY
		DelayMs(100);
		//CONFIGURE GPIOD.13->ODR=0
		GPIOD->ODR &= ~BV(13);
		//DELAY
			DelayMs(100);
	}
	return 0;
}
