/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "led.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	LedInit(LED_GREEN_PIN);
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	SystemInit();
	UartInit(9600);
	int choice;
	UartPuts("Enter the choice: ");
	char ch[2];
	UartGets(ch);
	sscanf(ch, "%d", &choice);
	do {

		switch (choice) {
		case 1:
			LedOn(LED_GREEN_PIN);
			DelayMs(1000);
			UartPuts("This is Green pin\r\n");
			break;
		case 2:
			LedOn(LED_GREEN_PIN);
			DelayMs(1000);
			UartPuts("This is Orange pin\r\n");
			break;
		case 3:
			LedOn(LED_GREEN_PIN);
			DelayMs(1000);
			UartPuts("This is Red pin\r\n");
			break;
		case 4:
			LedOn(LED_GREEN_PIN);
			DelayMs(1000);
			UartPuts("This is Blue pin\r\n");
		default:
			;

		}

	} while (1);

	DelayMs(1000);
//	while (1) {
//		LedBlink(LED_GREEN_PIN, 100);
//		LedBlink(LED_ORANGE_PIN, 100);
//		LedBlink(LED_RED_PIN, 100);
//		LedBlink(LED_BLUE_PIN, 100);
//	}
}
